### ISSUE TITLE
Variants' contexts get extended from the default context.

### ISSUE THREAD

**Issue by matijs** [frctl/fractal#123]
Variant contexts seem to be created by extending the default context. Consider the example below.

``` yaml

---
title: foo
context:
  options:
    - one
    - two
    - three
    - four
variants:
  -
    name: bar
    context:
      options:
        - alpha
        - beta
```

The options variable in the `bar` variant's context will contain `['alpha', 'beta', 'three', 'four']` which is not what I'd expect when setting `options` explicitly in the variant's own context. A workaround for now is to not define a context for the default version of a component.

**Comment by allmarkedup** [comment]
Hi @matijs that is actually the expected behaviour. The top-level context object is inherited and merged into all variants. Although the array behaviour does seem to trip people up so it may be worth revisiting...!

You can set context data for the default variant _only_ by explicitly defining a variant with the name `default` (this normally happens behind-the-scenes) and then giving it it's own data, something like:

```yaml
---
title: foo
context:
  title: This is inherited unless overriden in a variant
variants:
-
  name: default
  context:
    options:
      - foo
      - bar
  -
    name: bar
    context:
      title: this overrides the default title
      options:
        - alpha
        - beta
```
