### ISSUE TITLE
Help: Context for variants as sub-components

### ISSUE THREAD

**Issue by gunnx** [frctl/fractal#201]
I've just started today on trying out fractal as it looks really great and covers almost everything I was looking for in a pattern library tool.

I wanted to check something regarding variants as perhaps I'm not following the docs correctly.

I have a Button component with some variants, I've defined the variants via the config.yml file.

// Button.hbs
```
<button class="{{class}}">{{text}}</button>
```

// Button.config.json
```
status: wip
context:
  text: Primary
  class: button button--primary
variants:
- name: secondary
  context:
    text: Secondary
    class: button button--secondary
- name: back
  context:
    text: Back
    class: button button--back
```

I have a ButtonGroup component that include this component

// ButtonGroup.hbs
```
<div class="button-section">
  {{> @button--default }}
</div>
```

I'm trying to get that included variant to render with data but I've tried a few ways and its not working the include works but no data.

// ButtonGroup.config.yml
```
status: wip
context:
  button--default:
    text: Hello
    class: button
```

```
status: wip
context:
  button--default: '@button--default'
```

I can see the html being rendered and I can see the Context values, but clearly something not lining up. Any help welcome, thank you.

**Comment by dkhuntrods** [comment]
The scope of the partial block is the actual context, so you'd need to either pass the values directly (not ideal, as could lead to conflicts):
```
context: 
   text: Hello
   class: button
```
```
<div class="button-section">
  {{> @button--default }}
</div>
```
or pass an object and add that reference to the template:

```
context: 
   button: 
      text: Hello
      class: button
```
```
<div class="button-section">
  {{> @button--default button }}
</div>
```

You can also inline values:
```
context:
   otherVal: "Goodbye"
   otherClass: "button button--red"
```
```
<div class="button-section">
  {{> @button--default text=otherVal class=otherClass anotherValue="always-this-value" }}
</div>
```

I haven't tested that code, so the usual caveats. This is all primarily handlebars related, so its worth checking out their docs if you haven't before: http://handlebarsjs.com/
