### ISSUE TITLE
Support specifying preview templates on a variant basis

### ISSUE THREAD

**Issue by julmot** [frctl/fractal#280]
I'd like to specify a preview template for a specific variant within a component only, not for all variants. When specifying it for only one variant it will be shown for all variants though:

```yml
variants:
  - name: "primary-black"
    context:
      title: "Button Primary Black"
  - name: "primary-white"
    preview: "@dark"
    context:
      title: "Button Primary White"
  - name: "primary-gold"
    context:
      title: "Button Primary Gold"
  - name: "secondary"
    context:
      title: "Button Secondary"
  - name: "small"
    context:
      title: "Button small"
```

**Comment by samuells** [comment]
Hey this should work. Try do define default preview and set collated to false. This sample is working ok for me.

```yaml
title: Buttons
collated: false
preview: '@preview'
context:
  button:
    modifier: 'button'
variants:
  - name: Blue Button
    preview: '@preview-2'
    context:
      button:
        modifier: 'button--blue'
  - name: Style Blue Button
    preview: '@preview'
    context:
      button:
        modifier: 'button--blue'

```
