### ISSUE TITLE
Question: Can I read YAML front matter values inside a document’s body?

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#4]
Given the following documentation:

```
---
title: My Fabulous UI Toolkit
colors:
  primary:
    $color-darkgreen: "#166729"
    $color-darkgrey: "#585958"
    $color-pebble: "#dedbd2"
  shades:
    $color-palegreen: "#e5f0df"
    $color-lightgrey: "#ccc"
    $color-linen: "#f3f1ed"
    $color-light: "#fcfbf9"
  accents:
    $color-brightgreen: "#8dc63f"
    $color-magenta: "#d70171"
    $color-mustard: "#fbb531"
    $color-red: "#b40a16"
    $color-blue: "#3199d8"
---
This UI toolkit is a highly-modular design system for rapid web page development.
```

Can I access the additional front matter values inside the document body, for example:

```
## Colours
{{#each colors}}
    <ul class="palette">
        {{#each this}}
            <li class="palette__color" style="background-color: {{ this }}">{{@key}}</li>
        {{/each}}
    </ul>
{{/each}}
```

This particular example is taken from a port of some documentation written for Fabricator, but it’s a useful feature.

**Comment by paulrobertlloyd** [comment]
(There’s a larger documentation piece about reading data in more general terms, too)

**Comment by allmarkedup** [comment]
Yes - but like components the data needs to be in a `context:` object - i.e.

```yaml
---
title: My Fabulous UI Toolkit
context:
  colors:
    primary:
      $color-darkgreen: "#166729"
      $color-darkgrey: "#585958"
      $color-pebble: "#dedbd2"
    shades:
      $color-palegreen: "#e5f0df"
      $color-lightgrey: "#ccc"
      $color-linen: "#f3f1ed"
      $color-light: "#fcfbf9"
    accents:
      $color-brightgreen: "#8dc63f"
      $color-magenta: "#d70171"
      $color-mustard: "#fbb531"
      $color-red: "#b40a16"
      $color-blue: "#3199d8"
---
This UI toolkit is a highly-modular design system for rapid web page development.
```
