### ISSUE TITLE
In configuration the filename of view ignores letter case

### ISSUE THREAD

**Issue by supermueller** [frctl/fractal#651]
### Steps to reproduce the issue

1. Create a component with a variant.
1. Create a template file for the variant using camel case (e.g. `myComponent--templateForVariant.html`).
1. In the configuration of the variant specify the view template created (e.g. `view: 'myComponent--templateForVariant.html'`).

**Example for configuration:**
```
variants:
  -
    name: variant
    label: My Variant
    view: 'myComponent--templateForVariant.html'
````

### Result

Instead of the template of the variant the template of the component itself will be used for rendering.

### Expected behaviour

The template with the given filename should be used.

When using only lowercase in the configuration by leave the filename in camel case all works fine. By the way this is not the only issue when using file or component names with camel case.

### Context

-   Fractal version: 1.1.7
-   Node version: 10.16.3
